# Generated by Django 5.1.2 on 2024-11-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("in_class", "课内学习"),
                            ("out_of_class", "课外学习"),
                            ("work_task", "工作任务"),
                            ("self_improvement", "自我提升"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
